/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialogs;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Disciplina;
import model.Professor;

/**
 *
 * @author diego
 */
public class DlgEscolhaProfessor extends javax.swing.JDialog {
        Disciplina disciplina;
        Professor professorEscolhido;
        List<Professor> lista;

    /**
     * Creates new form DlgEscolhaProfessor
     */
    public DlgEscolhaProfessor(java.awt.Dialog parent, boolean modal, Disciplina disciplina) {
        super(parent, modal);
        initComponents();
        this.professorEscolhido = new Professor();
        this.disciplina = disciplina;
        
        loadProfessores();
    }
    
    public void loadProfessores(){
        FileReader f = null;
                try {
            this.lista = new ArrayList<>();
            f = new FileReader("ListagemProfessores.csv");
            Scanner arquivoLido = new Scanner(f);
            arquivoLido.useDelimiter("\n");

            String linhaLida = "";
            if (arquivoLido.hasNext()) //para evitar de ler arquivo vazio
            {
                linhaLida = arquivoLido.next();
            }

            while (arquivoLido.hasNext()) {
                linhaLida = arquivoLido.next();

                Professor p = new Professor();
                p.CSVToAtributo(linhaLida);
                this.lista.add(p);
            }
            //Atualiza a listagem
            edtListagemProfessores.setText(imprimirListaProfessores());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                f.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
        public String imprimirListaProfessores() {
        String listagemCompleta = "";

        for (int i = 0; i <= lista.size() - 1; i++) {
            Professor professor = lista.get(i);

            listagemCompleta = listagemCompleta + professor.toString();
        }
        return listagemCompleta;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panCpf = new javax.swing.JPanel();
        lblCpf = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        edtCpf = new javax.swing.JTextField();
        panEscolhido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblProfessorEscolhido = new javax.swing.JTextArea();
        panProfessores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagemProfessores = new javax.swing.JTextArea();
        btnAdicionarProfessor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Escolha um Professor");

        javax.swing.GroupLayout panTituloLayout = new javax.swing.GroupLayout(panTitulo);
        panTitulo.setLayout(panTituloLayout);
        panTituloLayout.setHorizontalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        panTituloLayout.setVerticalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        lblCpf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf.setText("CPF:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoescola/imagens/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        edtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCpfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCpfLayout = new javax.swing.GroupLayout(panCpf);
        panCpf.setLayout(panCpfLayout);
        panCpfLayout.setHorizontalGroup(
            panCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCpfLayout.createSequentialGroup()
                .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );
        panCpfLayout.setVerticalGroup(
            panCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCpfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addGroup(panCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblProfessorEscolhido.setColumns(20);
        lblProfessorEscolhido.setRows(5);
        jScrollPane2.setViewportView(lblProfessorEscolhido);

        javax.swing.GroupLayout panEscolhidoLayout = new javax.swing.GroupLayout(panEscolhido);
        panEscolhido.setLayout(panEscolhidoLayout);
        panEscolhidoLayout.setHorizontalGroup(
            panEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscolhidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panEscolhidoLayout.setVerticalGroup(
            panEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscolhidoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        panProfessores.setBackground(new java.awt.Color(255, 0, 102));

        edtListagemProfessores.setColumns(20);
        edtListagemProfessores.setRows(5);
        jScrollPane1.setViewportView(edtListagemProfessores);

        javax.swing.GroupLayout panProfessoresLayout = new javax.swing.GroupLayout(panProfessores);
        panProfessores.setLayout(panProfessoresLayout);
        panProfessoresLayout.setHorizontalGroup(
            panProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panProfessoresLayout.setVerticalGroup(
            panProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        btnAdicionarProfessor.setText("Adicionar Professor");
        btnAdicionarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panEscolhido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panProfessores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCpfActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String cpfEscolhido = edtCpf.getText();        
        if (!cpfEscolhido.isEmpty()) {
            int id = Integer.parseInt(cpfEscolhido);
            professorEscolhido = this.pesquisaProfessor(id);

            if (professorEscolhido == null) {
                JOptionPane.showMessageDialog(this, "Não existe este CPF.");
                lblProfessorEscolhido.setText("");
            } else {
                lblProfessorEscolhido.setText(professorEscolhido.toString());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdicionarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProfessorActionPerformed
            if (professorEscolhido == null) {
                int response = JOptionPane.showConfirmDialog(null,
                        "Nenhum professor foi escolhido. Deseja continuar?",
                        "Confirm",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.OK_OPTION) {
                    dispose();
            }
        } else {
            this.disciplina.setMinistrante(professorEscolhido);
            
            dispose();
        }
    }//GEN-LAST:event_btnAdicionarProfessorActionPerformed

    public Professor pesquisaProfessor(int id) {
        for (int i = 0; i <= lista.size() - 1; i++) {
            Professor prof = lista.get(i);

            if (Integer.parseInt(prof.getCpf()) == id) {
                return prof;
            }
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProfessor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextArea edtListagemProfessores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JTextArea lblProfessorEscolhido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panCpf;
    private javax.swing.JPanel panEscolhido;
    private javax.swing.JPanel panProfessores;
    private javax.swing.JPanel panTitulo;
    // End of variables declaration//GEN-END:variables
}
