/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialogs;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Disciplina;
import model.Professor;

/**
 *
 * @author diego
 */
public class DlgEscolhaAluno extends javax.swing.JDialog {
        Disciplina disciplina;
        Aluno alunoEscolhido;
        List<Aluno> lista;

    /**
     * Creates new form DlgEscolhaProfessor
     * @param parent
     * @param modal
     * @param disciplina
     */
    public DlgEscolhaAluno(java.awt.Dialog parent, boolean modal, Disciplina disciplina) {
        super(parent, modal);
        initComponents();
        this.alunoEscolhido = new Aluno();
        this.disciplina = disciplina;
        
        loadAlunos();
    }
    
    public void loadAlunos(){
        FileReader f = null;
                try {
            this.lista = new ArrayList<>();
            f = new FileReader("ListagemAlunos.csv");
            Scanner arquivoLido = new Scanner(f);
            arquivoLido.useDelimiter("\n");

            String linhaLida = "";
            if (arquivoLido.hasNext()) //para evitar de ler arquivo vazio
            {
                linhaLida = arquivoLido.next();
            }

            while (arquivoLido.hasNext()) {
                linhaLida = arquivoLido.next();

                Aluno a = new Aluno();
                a.CSVToAtributo(linhaLida);
                this.lista.add(a);
            }
            //Atualiza a listagem
            edtListagemAlunos.setText(imprimirListaAlunos());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                f.close();
            } catch (IOException ex) {
                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
        public String imprimirListaAlunos() {
        String listagemCompleta = "";

        for (int i = 0; i <= lista.size() - 1; i++) {
            Aluno aluno = lista.get(i);

            listagemCompleta = listagemCompleta + aluno.toString();
        }
        return listagemCompleta;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panCpf = new javax.swing.JPanel();
        lblMatricula = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        edtMatricula = new javax.swing.JTextField();
        panEscolhido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblAlunoEscolhido = new javax.swing.JTextArea();
        panAlunos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagemAlunos = new javax.swing.JTextArea();
        btnAdicionarAluno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Escolha um Aluno");

        javax.swing.GroupLayout panTituloLayout = new javax.swing.GroupLayout(panTitulo);
        panTitulo.setLayout(panTituloLayout);
        panTituloLayout.setHorizontalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        panTituloLayout.setVerticalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        lblMatricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatricula.setText("Matricula:");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoescola/imagens/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        edtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCpfLayout = new javax.swing.GroupLayout(panCpf);
        panCpf.setLayout(panCpfLayout);
        panCpfLayout.setHorizontalGroup(
            panCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCpfLayout.createSequentialGroup()
                .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
        );
        panCpfLayout.setVerticalGroup(
            panCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panCpfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panCpfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblAlunoEscolhido.setColumns(20);
        lblAlunoEscolhido.setRows(5);
        jScrollPane2.setViewportView(lblAlunoEscolhido);

        javax.swing.GroupLayout panEscolhidoLayout = new javax.swing.GroupLayout(panEscolhido);
        panEscolhido.setLayout(panEscolhidoLayout);
        panEscolhidoLayout.setHorizontalGroup(
            panEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscolhidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panEscolhidoLayout.setVerticalGroup(
            panEscolhidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEscolhidoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        panAlunos.setBackground(new java.awt.Color(255, 0, 102));

        edtListagemAlunos.setColumns(20);
        edtListagemAlunos.setRows(5);
        jScrollPane1.setViewportView(edtListagemAlunos);

        javax.swing.GroupLayout panAlunosLayout = new javax.swing.GroupLayout(panAlunos);
        panAlunos.setLayout(panAlunosLayout);
        panAlunosLayout.setHorizontalGroup(
            panAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panAlunosLayout.setVerticalGroup(
            panAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        btnAdicionarAluno.setText("Adicionar Aluno");
        btnAdicionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdicionarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panEscolhido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMatriculaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String matriculaEscolhida = edtMatricula.getText();        
        if (!matriculaEscolhida.isEmpty()) {
            String id = matriculaEscolhida;
            alunoEscolhido = this.pesquisaAluno(id);

            if (alunoEscolhido == null) {
                JOptionPane.showMessageDialog(this, "Não existe este CPF.");
                lblAlunoEscolhido.setText("");
            } else {
                lblAlunoEscolhido.setText(alunoEscolhido.toString());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAdicionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAlunoActionPerformed
            if (alunoEscolhido == null) {
                int response = JOptionPane.showConfirmDialog(null,
                        "Nenhum professor foi escolhido. Deseja continuar?",
                        "Confirm",
                        JOptionPane.OK_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.OK_OPTION) {
                    dispose();
            }
        } else {
            this.disciplina.getLstAlunos().add(alunoEscolhido);
            
            dispose();
        }
    }//GEN-LAST:event_btnAdicionarAlunoActionPerformed

    public Aluno pesquisaAluno(String id) {
        for (int i = 0; i <= lista.size() - 1; i++) {
            Aluno aluno = lista.get(i);

            if (aluno.getMatricula().equals(id)) {
                return aluno;
            }
        }
        return null;
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAluno;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextArea edtListagemAlunos;
    private javax.swing.JTextField edtMatricula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lblAlunoEscolhido;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panAlunos;
    private javax.swing.JPanel panCpf;
    private javax.swing.JPanel panEscolhido;
    private javax.swing.JPanel panTitulo;
    // End of variables declaration//GEN-END:variables
}
